property:
    test:
        name: property depth test

propertyTest: test
propertyTestList: a,b,c

---
fruit:
    list:
        - name: banana
          color: yellow
        - name: apple
          color: red
        - name: water melon
          color: green

---
fruit-property.color-name: red
fruit-property.color_name: red
fruit-property.colorName: red
fruit-property.colorname: red

